/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./login/Templates/**/*.html'],
  safelist: [
    'hidden',
    'flex',
    'grade-saved',
    'error-range',
    // Clases aplicadas desde JavaScript (no aparecen en el HTML estático)
    'border-red-500',
    'border-gray-200',
    'focus:border-red-500',
    'focus:border-blue-500',
    'focus:ring-red-500',
    'bg-green-50',
    'text-green-700',
    'border-green-200',
    'bg-red-50',
    'text-red-700',
    'border-red-200',
    'bg-green-100',
    'text-green-800',
    'border-green-400',
    'p-4',
    'rounded-lg',
    'bg-red-100',
    'text-red-800',
    'border-red-400',
    'bg-gray-300',
    'bg-red-500',
    'bg-amber-500',
    'bg-green-500',
    'bg-green-600',
    'text-red-500',
    'text-amber-500',
    'text-green-600',
    'text-gray-400',
    'inline-flex',
    'items-center',
    'gap-1',
    'px-3',
    'py-1',
    'rounded-full',
    'text-xs',
    'font-bold',
    'bg-blue-100',
    'text-blue-800',
    'bg-gray-100',
    'text-gray-600',
    'opacity-60',
    'cursor-not-allowed',
    'bg-gray-100',
    'bg-blue-600',
    'text-white',
    'bg-gray-200',
    'text-gray-700',
    'hover:bg-gray-300',
    'text-lg',
    'text-red-600',
    'mt-1',
    'text-red-600',
    'text-red-500',
    'mt-1',
    'h-full',
    'rounded-full',
    'transition-all',
    'duration-300',
    'text-[10px]',
    'uppercase',
    'tracking-wider',
    'px-3',
    'py-2',
    'rounded-lg',
    'transition',
    'border',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
