# Generated by Django 6.0.3 on 2026-05-10 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(editable=False, max_length=25, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('maestro', 'Maestro'), ('alumno', 'Alumno'), ('administrativo', 'Administrativo')], max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.usuarios')),
                ('puesto', models.CharField(choices=[('Director', 'Director'), ('Subdirector', 'Subdirector'), ('Auxiliar', 'Auxiliar')], max_length=20)),
                ('nivel_prioridad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Administrativos',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.usuarios')),
                ('departamento', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Administrativo',
                'verbose_name_plural': 'Administrativos',
                'db_table': 'administrativos',
            },
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.usuarios')),
                ('carrera', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
                ('periodo_ingreso', models.CharField(max_length=10)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja'), ('Egresado', 'Egresado')], default='Activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumnos',
            },
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.usuarios')),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('correo_inst', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Dato Personal',
                'verbose_name_plural': 'Datos Personales',
                'db_table': 'datos_personales',
            },
        ),
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.usuarios')),
                ('departamento', models.CharField(max_length=100)),
                ('cubiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('grado_academico', models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Maestria', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=20)),
            ],
            options={
                'verbose_name': 'Maestro',
                'verbose_name_plural': 'Maestros',
                'db_table': 'maestros',
            },
        ),
    ]
