# Generated by Django 6.0.3 on 2026-05-10 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id_ciclo_escolar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciclo', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciclo Escolar',
                'verbose_name_plural': 'Ciclos Escolares',
                'db_table': 'ciclo_escolar',
            },
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_ciclo_escolar',
            field=models.ForeignKey(blank=True, db_column='id_ciclo_escolar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.cicloescolar'),
        ),
    ]
