# Generated by Django 6.0.3 on 2026-05-10 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_cicloescolar_administrador_id_ciclo_escolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cicloescolar',
            name='estatus',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id_ciclo_escolar',
            field=models.ForeignKey(db_column='id_ciclo_escolar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.cicloescolar'),
        ),
    ]
