# Generated by Django 6.0.3 on 2026-05-12 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_add_fk_ciclo_escolar_to_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'carrera',
            },
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='carrera',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='id_carrera',
            field=models.ForeignKey(db_column='id_carrera', null=True, on_delete=django.db.models.deletion.PROTECT, to='login.carrera'),
        ),
    ]
