# Generated by Django 6.0.3 on 2026-05-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_add_materia_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='clave',
        ),
        migrations.AddField(
            model_name='carrera',
            name='siglas',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='id_carrera',
            field=models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.carrera'),
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
