# Generated by Django 6.0.3 on 2026-05-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_fix_alumnos_carrera_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='siglas',
        ),
        migrations.AddField(
            model_name='carrera',
            name='clave',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
