# Generated by Django 6.0.3 on 2026-05-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_change_siglas_to_clave_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='clave',
            field=models.CharField(default='', max_length=10),
        ),
    ]
