# Generated by Django 6.0.3 on 2026-05-13 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno')], max_length=20)),
                ('cupo_maximo', models.IntegerField(default=0)),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_carrera', models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.CASCADE, to='login.carrera')),
                ('id_ciclo_escolar', models.ForeignKey(db_column='id_ciclo_escolar', on_delete=django.db.models.deletion.CASCADE, to='login.cicloescolar')),
                ('id_maestro_tutor', models.ForeignKey(blank=True, db_column='id_maestro_tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.maestros')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo',
            },
        ),
    ]
