# Generated by Django 6.0.3 on 2026-05-13 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='creditos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('Activa', 'Activa'), ('Baja', 'Baja'), ('Reinscripcion', 'Reinscripcion')], default='Activa', max_length=20)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='login.alumnos')),
                ('id_ciclo_escolar', models.ForeignKey(db_column='id_ciclo_escolar', on_delete=django.db.models.deletion.CASCADE, to='login.cicloescolar')),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='login.grupo')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripcion',
            },
        ),
    ]
