# Generated by Django 6.0.3 on 2026-05-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_materia_creditos_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='id_maestro_tutor',
        ),
    ]
