# Generated by Django 6.0.3 on 2026-05-13 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_grupo_id_maestro_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionMateria',
            fields=[
                ('id_asignacion_materia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('Activa', 'Activa'), ('Finalizada', 'Finalizada'), ('Suspendida', 'Suspendida')], default='Activa', max_length=20)),
                ('id_ciclo_escolar', models.ForeignKey(db_column='id_ciclo_escolar', on_delete=django.db.models.deletion.CASCADE, to='login.cicloescolar')),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='login.grupo')),
                ('id_maestro', models.ForeignKey(db_column='id_maestro', on_delete=django.db.models.deletion.CASCADE, to='login.maestros')),
                ('id_materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.CASCADE, to='login.materia')),
            ],
            options={
                'verbose_name': 'Asignacion de Materia',
                'verbose_name_plural': 'Asignaciones de Materia',
                'db_table': 'asignacion_materia',
                'constraints': [models.UniqueConstraint(fields=('id_materia', 'id_maestro', 'id_grupo', 'id_ciclo_escolar'), name='uniq_asignacion_materia')],
            },
        ),
    ]
