# Generated by Django 6.0.3 on 2026-05-13 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_asignacionmateria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Reprogramado', 'Reprogramado')], default='Activo', max_length=20)),
                ('id_asignacion_materia', models.ForeignKey(db_column='id_asignacion_materia', on_delete=django.db.models.deletion.CASCADE, to='login.asignacionmateria')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
            },
        ),
    ]
