# Generated by Django 6.0.3 on 2026-05-13 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField()),
                ('estatus', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Tarde', 'Tarde'), ('Justificado', 'Justificado')], default='Presente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_horario', models.ForeignKey(db_column='id_horario', on_delete=django.db.models.deletion.CASCADE, to='login.horario')),
                ('id_inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='login.inscripcion')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'constraints': [models.UniqueConstraint(fields=('id_inscripcion', 'id_horario', 'fecha_asistencia'), name='uniq_asistencia_por_clase_fecha')],
            },
        ),
    ]
