# Generated by Django 6.0.3 on 2026-05-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Parcial', 'Parcial'), ('Final', 'Final'), ('Extraordinario', 'Extraordinario'), ('Regularizacion', 'Regularización')], default='Parcial', max_length=20)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_asignacion_materia', models.ForeignKey(db_column='id_asignacion_materia', on_delete=django.db.models.deletion.CASCADE, to='login.asignacionmateria')),
                ('id_inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='login.inscripcion')),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacion',
                'constraints': [models.UniqueConstraint(fields=('id_inscripcion', 'id_asignacion_materia', 'tipo'), name='uniq_calificacion_por_tipo')],
            },
        ),
    ]
