# Generated by Django 6.0.3 on 2026-05-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.IntegerField(default=1),
        ),
    ]
