# Generated by Django 6.0.3 on 2026-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_materia_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloescolar',
            name='periodo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='nombre_ciclo',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
