# Generated by Django 6.0.3 on 2026-05-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_cicloescolar_periodo_alter_cicloescolar_nombre_ciclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='aula',
        ),
    ]
