# Generated by Django 6.0.3 on 2026-05-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_asistencia_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contrasena_temporal',
            field=models.BooleanField(default=False),
        ),
    ]
