# Generated by Django 6.0.3 on 2026-05-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_usuarios_contrasena_temporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
