# Generated by Django 6.0.3 on 2026-05-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_remove_django_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='correo_inst',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='curp',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True),
        ),
    ]
