# Generated by Django 6.0.3 on 2026-05-24 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_alter_datospersonales_correo_inst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cuenta_bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_bloqueo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='intentos_fallidos_login',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LogCalificacion',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar')], max_length=20)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unidad', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_alumno', models.ForeignKey(blank=True, db_column='id_alumno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_calificaciones', to='login.alumnos')),
                ('id_calificacion', models.ForeignKey(blank=True, db_column='id_calificacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='login.calificacion')),
                ('id_materia', models.ForeignKey(blank=True, db_column='id_materia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_calificaciones', to='login.materia')),
                ('id_usuario_modifico', models.ForeignKey(db_column='id_usuario_modifico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_calificaciones', to='login.usuarios')),
            ],
            options={
                'verbose_name': 'Log de Calificación',
                'verbose_name_plural': 'Logs de Calificaciones',
                'db_table': 'log_calificacion',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
