# Generated by Django 6.0.3 on 2026-05-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_usuarios_cuenta_bloqueada_usuarios_fecha_bloqueo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('id_asignacion_materia', 'dia_semana', 'hora_inicio', 'hora_fin'), name='uniq_horario_completo', violation_error_message='Ya existe un horario idéntico para esta asignación'),
        ),
    ]
