# Generated by Django 6.0.3 on 2026-06-07 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_usuarios_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRecuperacionContrasena',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('correo_destino', models.EmailField(max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to='login.usuarios')),
            ],
            options={
                'verbose_name': 'Token de recuperación de contraseña',
                'verbose_name_plural': 'Tokens de recuperación de contraseña',
                'db_table': 'token_recuperacion_contrasena',
                'indexes': [models.Index(fields=['id_usuario', 'creado_en'], name='token_recup_id_usua_9f5c8d_idx')],
            },
        ),
    ]
