# Generated by Django 6.0.3 on 2026-06-09 03:27

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_django_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='id_carrera',
            field=models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.CASCADE, to='login.carrera'),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='nombre_ciclo',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='clave',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='carrera',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='uniq_carrera_nombre_lower', violation_error_message='Ya existe una carrera con ese nombre.'),
        ),
        migrations.AddConstraint(
            model_name='carrera',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('clave'), condition=models.Q(('clave', ''), _negated=True), name='uniq_carrera_clave_lower', violation_error_message='Ya existe una carrera con esa clave'),
        ),
        migrations.AddConstraint(
            model_name='cicloescolar',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='ciclo_fecha_fin_posterior', violation_error_message='La fecha de fin debe ser posterior a la de inicio'),
        ),
        migrations.AddConstraint(
            model_name='datospersonales',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('correo_inst'), condition=models.Q(('correo_inst__isnull', False), models.Q(('correo_inst', ''), _negated=True)), name='uniq_datos_personales_correo_lower', violation_error_message='Este correo electrónico ya está registrado en el sistema.'),
        ),
        migrations.AddConstraint(
            model_name='datospersonales',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('curp'), condition=models.Q(('curp__isnull', False), models.Q(('curp', ''), _negated=True)), name='uniq_datos_personales_curp_lower', violation_error_message='Esta CURP ya está registrada en el sistema.'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('id_alumno', 'id_grupo', 'id_ciclo_escolar'), name='uniq_inscripcion_alumno_grupo_ciclo', violation_error_message='El alumno ya está inscrito en ese grupo para ese ciclo'),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('clave'), name='uniq_materia_clave_lower', violation_error_message='Ya existe una materia con ese código'),
        ),
    ]
