# Generated by Django 6.0.3 on 2026-06-09 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_integrity_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='id_carrera',
            field=models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.PROTECT, to='login.carrera'),
        ),
        migrations.AlterField(
            model_name='asignacionmateria',
            name='id_ciclo_escolar',
            field=models.ForeignKey(db_column='id_ciclo_escolar', on_delete=django.db.models.deletion.PROTECT, to='login.cicloescolar'),
        ),
        migrations.AlterField(
            model_name='asignacionmateria',
            name='id_grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.PROTECT, to='login.grupo'),
        ),
        migrations.AlterField(
            model_name='asignacionmateria',
            name='id_maestro',
            field=models.ForeignKey(db_column='id_maestro', on_delete=django.db.models.deletion.PROTECT, to='login.maestros'),
        ),
        migrations.AlterField(
            model_name='asignacionmateria',
            name='id_materia',
            field=models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.PROTECT, to='login.materia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='id_inscripcion',
            field=models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.PROTECT, to='login.inscripcion'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='id_asignacion_materia',
            field=models.ForeignKey(db_column='id_asignacion_materia', on_delete=django.db.models.deletion.PROTECT, to='login.asignacionmateria'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='id_inscripcion',
            field=models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.PROTECT, to='login.inscripcion'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id_carrera',
            field=models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.PROTECT, to='login.carrera'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id_ciclo_escolar',
            field=models.ForeignKey(db_column='id_ciclo_escolar', on_delete=django.db.models.deletion.PROTECT, to='login.cicloescolar'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='id_asignacion_materia',
            field=models.ForeignKey(db_column='id_asignacion_materia', on_delete=django.db.models.deletion.PROTECT, to='login.asignacionmateria'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id_alumno',
            field=models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.PROTECT, to='login.alumnos'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id_ciclo_escolar',
            field=models.ForeignKey(db_column='id_ciclo_escolar', on_delete=django.db.models.deletion.PROTECT, to='login.cicloescolar'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id_grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.PROTECT, to='login.grupo'),
        ),
    ]
