# Generated by Django 6.0.3 on 2026-06-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_protect_related_records'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cicloescolar',
            constraint=models.CheckConstraint(condition=models.Q(('periodo__in', ['A', 'B'])), name='ciclo_periodo_valido', violation_error_message='Selecciona un periodo válido (A o B)'),
        ),
    ]
