# Generated by Django 6.0.3 on 2026-06-09 04:51

import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0038_ciclo_periodo_valido'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cicloescolar',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_ciclo', django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast(django.db.models.functions.datetime.ExtractYear('fecha_inicio'), models.CharField(max_length=4)), models.Value('-'), models.F('periodo'), output_field=models.CharField(max_length=50)))), name='ciclo_nombre_coherente', violation_error_message='El nombre del ciclo debe coincidir con el año de inicio y el periodo'),
        ),
    ]
