# Generated by Django 6.0.3 on 2026-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_ciclo_nombre_coherente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.IntegerField(default=3),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.CheckConstraint(condition=models.Q(('creditos__gte', 1), ('creditos__lte', 10)), name='materia_creditos_rango', violation_error_message='Los créditos deben estar entre 1 y 10'),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.CheckConstraint(condition=models.Q(('semestre__gte', 1), ('semestre__lte', 9)), name='materia_semestre_rango', violation_error_message='El semestre debe estar entre 1 y 9'),
        ),
    ]
