# Generated by Django 6.0.3 on 2026-06-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_materia_creditos_semestre_rango'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materia',
            name='materia_semestre_rango',
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.CheckConstraint(condition=models.Q(('semestre__gte', 1), ('semestre__lte', 12)), name='materia_semestre_rango', violation_error_message='El semestre debe estar entre 1 y 12'),
        ),
    ]
