# Generated by Django 6.0.3 on 2026-06-10 15:19

from datetime import date, timedelta

from django.db import migrations, models


def _max_dia_mes(mes: int) -> int:
    if mes == 2:
        return 28
    if mes in (4, 6, 9, 11):
        return 30
    return 31


def corregir_ciclos_periodo_mes(apps, schema_editor):
    """Ajusta fecha_inicio para que coincida con el periodo antes del CHECK."""
    CicloEscolar = apps.get_model('login', 'CicloEscolar')

    for ciclo in CicloEscolar.objects.all():
        mes = ciclo.fecha_inicio.month
        if ciclo.periodo == 'A' and (mes <= 6 or mes == 7):
            continue
        if ciclo.periodo == 'B' and mes >= 8:
            continue

        nuevo_mes = 2 if ciclo.periodo == 'A' else 8
        dia = min(ciclo.fecha_inicio.day, _max_dia_mes(nuevo_mes))
        nuevo_inicio = date(ciclo.fecha_inicio.year, nuevo_mes, dia)
        duracion = ciclo.fecha_fin - ciclo.fecha_inicio
        if duracion.days <= 0:
            duracion = timedelta(days=150)

        ciclo.fecha_inicio = nuevo_inicio
        ciclo.fecha_fin = nuevo_inicio + duracion
        ciclo.nombre_ciclo = f'{nuevo_inicio.year}-{ciclo.periodo}'
        ciclo.save(update_fields=['fecha_inicio', 'fecha_fin', 'nombre_ciclo'])


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_materia_semestre_max_12'),
    ]

    operations = [
        migrations.RunPython(corregir_ciclos_periodo_mes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cicloescolar',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('fecha_inicio__month__lte', 6), ('periodo', 'A')),
                    models.Q(('fecha_inicio__month', 7), ('periodo', 'A')),
                    models.Q(('fecha_inicio__month__gte', 8), ('periodo', 'B')),
                    _connector='OR',
                ),
                name='ciclo_periodo_coherente_mes',
                violation_error_message='El periodo no coincide con el mes de la fecha de inicio',
            ),
        ),
    ]
